:Author: SaromTorres
:Email: sarom.t@aluno.ifsc.edu.br
:Date: 06/06/2019
:Revision: version#
:License: Public Domain

= Project: Aninhamento e semaforo contador

== OBJETIVO: 
Realizar o aninhamento de interrupções colocando prioridades diferentes para demonstrar as hierarquias de execução.

== APLICAÇÃO: 
Foram criadas dias interrupções associadas a duas diferentes tarefas, no qual cada uma teria uma prioridade diferente. A tarefa responsável por acender o LED verde teria prioridade maior em relação a tarefa que piscaria o LED vermelho. Sendo assim através de um botão o LED vermelho seria acionado e piscaria indefinidamente. Enquanto isso o botão que acende o LED verde seria pressionado o que faria o LED vermelho interromper instantaneamente e o LED verde piscaria.

== ANÁLISE: 
Segundo o manual apenas alguns FreeRTOS implementam prioridades para interrupções sendo que o utilizado no projeto não possui nenhuma das constantes para configuração de prioridades citadas abaixo, o que impossibilita classificar uma ISR com mais ou menos prioridade.

configMAX_SYSCALL_INTERRUPT_PRIORITY 
configMAX_API_CALL_INTERRUPT_PRIORITY
configKERNEL_INTERRUPT_PRIORITY

Além disso o sistema não possui a função portYIELD_FROM_ISR(), o que impossibilitaria a troca de contexto automática entre uma task e outra.
Devido aos motivos supracitados não pode ser implementado o aninhamento de interrupções o que resultou em um código no qual duas tarefas geradas por interrupções se executam simultaneamente.
